#!/bin/bash

STAGED_FILES=$(git diff --cached --name-only | grep "\.tsx\|\.ts\|\.js\?$")
STAGED_SCSS_FILES=$(git diff --cached --name-only | grep "\.scss\?$")

ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"
STYLELINT="$(git rev-parse --show-toplevel)/node_modules/.bin/stylelint"

if [[ "$STAGED_FILES" = "" ]] && [[ "$STAGED_SCSS_FILES" = "" ]]; then
  exit 0
fi

PASS=true

printf "\nValidating Javascript:\n"

# Check for eslint
if [[ ! -x "$ESLINT" ]]; then
  printf "\t\033[41mPlease install ESlint\033[0m (npm i --save-dev eslint)"
  exit 1
fi

for FILE in $STAGED_FILES
  do
  if [ -f "$FILE" ]; then
    "$ESLINT" "$FILE"

    if [[ "$?" == 0 ]]; then
      printf "\t\033[32mESLint Passed: $FILE\033[0m\n"
    else
      printf "\t\033[41mESLint Failed: $FILE\033[0m\n"
      PASS=false
    fi
  fi
done

printf "\nJavascript validation completed!\n"

printf "\nValidating SCSS styles:\n"

for FILE in $STAGED_SCSS_FILES
  do
  if [ -f "$FILE" ]; then
    "$STYLELINT" "$FILE"

    if [[ "$?" == 0 ]]; then
      printf "\t\033[32mStylelint Passed: $FILE\033[0m\n"
    else
      printf "\t\033[41mStylelint Failed: $FILE\033[0m\n"
      PASS=false
    fi
  fi
done

printf "\nSCSS styles validation completed!\n"

if ! $PASS; then
  printf "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass the lint process but do not. Please fix the errors and try again.\n"
  exit 1
else
  printf "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

exit $?